---
- name: Provision Image Dinivas RabbitMQ Node to build
  hosts: rabbitmq-nodes
  become: true
  vars:
    erlang_version: 21.3.8.8
    rabbitmq_plugins:
      - rabbitmq_management
      - rabbitmq_management_agent
      - rabbitmq_shovel
      - rabbitmq_prometheus
      - rabbitmq_mqtt
      - rabbitmq_peer_discovery_consul
      - rabbitmq_web_mqtt
      - rabbitmq_federation
      - rabbitmq_federation_management
  pre_tasks:
    - name: Download erlang rpm
      get_url:
        url: "https://github.com/rabbitmq/erlang-rpm/releases/download/v{{ erlang_version }}/erlang-{{ erlang_version }}-1.el7.x86_64.rpm"
        dest: "/tmp/erlang-{{ erlang_version }}-1.el7.x86_64.rpm"
        mode: '0600'
    - name: Install Erlang package
      yum:
        name: "/tmp/erlang-{{ erlang_version }}-1.el7.x86_64.rpm"
        state: present
  roles:
    - role: geerlingguy.rabbitmq
      rabbitmq_daemon: rabbitmq-server
      rabbitmq_state: stopped
      rabbitmq_enabled: false
      rabbitmq_version: "3.8.0"
  tasks:
    - name: Source plugins file
      template:
        src: "{{ playbook_dir }}/templates/rabbitmq-plugins.j2"
        dest: /etc/rabbitmq/enabled_plugins
        mode: 0644
        owner: rabbitmq
        group: rabbitmq
    - name: Source configuration file
      template:
        src: "{{ playbook_dir }}/templates/rabbitmq.conf.j2"
        dest: /etc/rabbitmq/rabbitmq.conf
        mode: 0644
        owner: rabbitmq
        group: rabbitmq