---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: packer-dinivas-rabbitmq-1
    image: centos:7
    groups:
      - rabbitmq-nodes
    published_ports:
      - 0.0.0.0:15677:15672/tcp
    privileged: True
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: packer-dinivas-rabbitmq-2
    image: centos:7
    groups:
      - rabbitmq-nodes
    published_ports:
      - 0.0.0.0:15678:15672/tcp
    privileged: True
    command: '/sbin/init'
    cap_add: ['SYS_ADMIN', 'SETPCAP']
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  playbooks:
    converge: ../../playbook.yml
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
